"""add_xendit_payment_columns

Revision ID: 854deab0b964
Revises: 
Create Date: 2026-04-05 16:06:20.720080+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854deab0b964'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xendit_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('xendit_payment_method_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'has_used_trial',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'has_used_trial',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('users', 'xendit_payment_method_id')
    op.drop_column('users', 'xendit_customer_id')
    # ### end Alembic commands ###
